version: "3"
services:
  app:
    restart: unless-stopped
    image: ghcr.io/sefirosweb/minecraft-legion:latest
    environment:
      SERVER: "${SERVER:-host.docker.internal}" # Minecraft Server // "localhost" in reality is host.docker.internal 
      PORT: "${PORT:-25565}" # Minecraft Port
      MASTERS: "${MASTERS:-player1}" # Names of master players, separated with comma
      WEB_SERVER_PASSWORD: "${WEB_SERVER_PASSWORD:-admin}" # Password to login into front end
      AUTO_RESTART: ${AUTO_RESTART:-1} # If bot crashes they auto reload again
      CUSTOM_START: ${CUSTOM_START:-0} # If you want to do some actions before start bot, you can put here your own custom.js file (used for logging into servers)
      SECRET_TOKEN: ${SECRET_TOKEN:-0} # This token is used to encrypt your session, must be randomnly and dont share it

    volumes:
      - "./botConfig:/app/core/botConfig" # Folder on saved bot configuration
      - "./custom_start:/app/core/custom_start" # Folder is execute custom start before start bot
      - "./db:/app/db" # This file stored session info and all bot config


    ports:
      - "${FORWARD_WEB_PORT:-80}:80" # Web port
      - "4500-4550:4500-4550" # Ports used to attach viewers
